// Flat block model — the single source of truth for a lesson body.
//
// Lesson = { id, title, blocks: Block[] }
// Block  = { id, type, content, role? }
//
// Content shapes per type:
//   heading:   string (HTML for rich text)
//   text:      string (HTML)
//   tip:       string (HTML)
//   callout:   string (HTML)
//   image:     { src: string, caption: string, width: 'small'|'medium'|'large'|'full' }
//   video:     { url: string, caption: string }
//   checklist: Array<{ id: string, text: string, done: boolean }>
//   steps:     Array<{ id: string, text: string }>
//   divider:   null
//
// `role` is an optional tag ('script' | 'demoSteps' | 'mistakes' | 'tip') on
// blocks generated by the AI so Match-Style / Improve / Refine can target
// them. Manually-inserted blocks don't have a role and are left alone by
// role-targeted AI operations.

export const BLOCK_TYPES = [
  'heading',
  'text',
  'tip',
  'callout',
  'image',
  'video',
  'checklist',
  'steps',
  'divider',
];

export const IMAGE_WIDTHS = ['small', 'medium', 'large', 'full'];

let _idCounter = 0;
function nextSuffix() {
  _idCounter = (_idCounter + 1) % 1_000_000;
  return `${Date.now()}-${_idCounter.toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

export function makeBlockId() {
  return `b-${nextSuffix()}`;
}

export function makeItemId() {
  return `i-${nextSuffix()}`;
}

function emptyContentFor(type) {
  switch (type) {
    case 'image':
      return { src: '', caption: '', width: 'full' };
    case 'video':
      return { url: '', caption: '' };
    case 'checklist':
    case 'steps':
      return [];
    case 'divider':
      return null;
    default:
      return '';
  }
}

export function makeBlock(type, patch = {}) {
  const t = BLOCK_TYPES.includes(type) ? type : 'text';
  return {
    id: makeBlockId(),
    type: t,
    content: emptyContentFor(t),
    ...patch,
  };
}

// Guarantees a block object is well-formed. Unknown types fall back to text.
export function normalizeBlock(raw) {
  if (!raw || typeof raw !== 'object') return makeBlock('text');
  const type = BLOCK_TYPES.includes(raw.type) ? raw.type : 'text';
  const base = {
    id: typeof raw.id === 'string' && raw.id ? raw.id : makeBlockId(),
    type,
    role: typeof raw.role === 'string' ? raw.role : undefined,
  };

  switch (type) {
    case 'image': {
      const c = raw.content || {};
      return {
        ...base,
        content: {
          src: typeof c.src === 'string' ? c.src : '',
          caption: typeof c.caption === 'string' ? c.caption : '',
          width: IMAGE_WIDTHS.includes(c.width) ? c.width : 'full',
        },
      };
    }
    case 'video': {
      const c = raw.content || {};
      return {
        ...base,
        content: {
          url: typeof c.url === 'string' ? c.url : '',
          caption: typeof c.caption === 'string' ? c.caption : '',
        },
      };
    }
    case 'checklist': {
      const items = Array.isArray(raw.content) ? raw.content : [];
      return {
        ...base,
        content: items.map((it) => ({
          id: typeof it?.id === 'string' ? it.id : makeItemId(),
          text: typeof it?.text === 'string' ? it.text : '',
          done: Boolean(it?.done),
        })),
      };
    }
    case 'steps': {
      const items = Array.isArray(raw.content) ? raw.content : [];
      return {
        ...base,
        content: items.map((it) => ({
          id: typeof it?.id === 'string' ? it.id : makeItemId(),
          text: typeof it?.text === 'string' ? it.text : '',
        })),
      };
    }
    case 'divider':
      return { ...base, content: null };
    default:
      return {
        ...base,
        content: typeof raw.content === 'string' ? raw.content : '',
      };
  }
}

// Strip HTML → plain text (for AI payloads, exports, emptiness checks).
export function htmlToPlain(html) {
  if (typeof html !== 'string' || !html) return '';
  if (typeof document === 'undefined') return html.replace(/<[^>]*>/g, '');
  const el = document.createElement('div');
  el.innerHTML = html;
  return el.textContent || '';
}

export function blockHasContent(block) {
  if (!block) return false;
  switch (block.type) {
    case 'image':
      return Boolean(block.content?.src);
    case 'video':
      return Boolean(block.content?.url);
    case 'checklist':
    case 'steps':
      return Array.isArray(block.content) && block.content.some((it) => htmlToPlain(it.text).trim());
    case 'divider':
      return true;
    default:
      return Boolean(htmlToPlain(block.content || '').trim());
  }
}

export function blockToPlainText(block) {
  if (!block) return '';
  switch (block.type) {
    case 'image':
      return block.content?.caption || '';
    case 'video':
      return block.content?.caption || block.content?.url || '';
    case 'checklist':
      return (block.content || [])
        .map((it) => `${it.done ? '[x]' : '[ ]'} ${htmlToPlain(it.text)}`.trim())
        .filter(Boolean)
        .join('\n');
    case 'steps':
      return (block.content || [])
        .map((it, i) => {
          const t = htmlToPlain(it.text).trim();
          return t ? `${i + 1}. ${t}` : '';
        })
        .filter(Boolean)
        .join('\n');
    case 'divider':
      return '---';
    default:
      return htmlToPlain(block.content || '');
  }
}

export function cloneBlock(block) {
  if (!block) return block;
  const id = makeBlockId();
  switch (block.type) {
    case 'checklist':
    case 'steps':
      return {
        ...block,
        id,
        content: (block.content || []).map((it) => ({ ...it, id: makeItemId() })),
      };
    case 'image':
    case 'video':
      return { ...block, id, content: { ...block.content } };
    case 'divider':
      return { ...block, id, content: null };
    default:
      return { ...block, id };
  }
}
